#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v10
# autospec commit: 5905be9
#
# Source0 file verified with key 0x8533F94B6379E538 (wolf@wolfsden.cz)
#
Name     : gengetopt
Version  : 2.23
Release  : 3
URL      : https://ftp.gnu.org/gnu/gengetopt/gengetopt-2.23.tar.xz
Source0  : https://ftp.gnu.org/gnu/gengetopt/gengetopt-2.23.tar.xz
Source1  : https://ftp.gnu.org/gnu/gengetopt/gengetopt-2.23.tar.xz.sig
Source2  : 8533F94B6379E538.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: gengetopt-bin = %{version}-%{release}
Requires: gengetopt-data = %{version}-%{release}
Requires: gengetopt-info = %{version}-%{release}
Requires: gengetopt-license = %{version}-%{release}
Requires: gengetopt-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : gnupg
BuildRequires : help2man
BuildRequires : texinfo
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
GNU Gengetopt
This program generates a C function that uses /getopt_long/ function to
parse the command line options, to validate them and fills a /struct/ .

%package bin
Summary: bin components for the gengetopt package.
Group: Binaries
Requires: gengetopt-data = %{version}-%{release}
Requires: gengetopt-license = %{version}-%{release}

%description bin
bin components for the gengetopt package.


%package data
Summary: data components for the gengetopt package.
Group: Data

%description data
data components for the gengetopt package.


%package doc
Summary: doc components for the gengetopt package.
Group: Documentation
Requires: gengetopt-man = %{version}-%{release}
Requires: gengetopt-info = %{version}-%{release}

%description doc
doc components for the gengetopt package.


%package info
Summary: info components for the gengetopt package.
Group: Default

%description info
info components for the gengetopt package.


%package license
Summary: license components for the gengetopt package.
Group: Default

%description license
license components for the gengetopt package.


%package man
Summary: man components for the gengetopt package.
Group: Default

%description man
man components for the gengetopt package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 8533F94B6379E538' gpg.status
%setup -q -n gengetopt-2.23
cd %{_builddir}/gengetopt-2.23
pushd ..
cp -a gengetopt-2.23 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713291580
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1713291580
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gengetopt
cp %{_builddir}/gengetopt-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gengetopt/af0a86c5fbc3c0fa0cbf93f8a8a0adf00ace50b3 || :
cp %{_builddir}/gengetopt-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/gengetopt/ed4c9b81ee1d280a47cf58374e94c1e3fc36beae || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gengetopt
/usr/bin/gengetopt

%files data
%defattr(-,root,root,-)
/usr/share/gengetopt/getopt.c
/usr/share/gengetopt/getopt1.c
/usr/share/gengetopt/gnugetopt.h

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/gengetopt/*

%files info
%defattr(0644,root,root,0755)
/usr/share/info/gengetopt.info
/usr/share/info/index.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gengetopt/af0a86c5fbc3c0fa0cbf93f8a8a0adf00ace50b3
/usr/share/package-licenses/gengetopt/ed4c9b81ee1d280a47cf58374e94c1e3fc36beae

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gengetopt.1
